### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ghost** [dankert/openrat-cms#2]
I was trying the latest tagged release and it fails to work at all because it fails to initialize my MySQL database due to syntax errors. Is there going to be a new release anytime soon?

**Comment by dankert** [comment]
Hello braewoods,
sorry for the late answer. 
Which version of MySql database do you use?

The easiest way is to use a docker compose environment as explained here:
https://github.com/dankert/openrat-cms/blob/master/README.md

**Comment by dankert** [comment]
Just released the 2.0.5
